import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Turtle Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <h1 className="text-4xl font-bold">Turtle Bot</h1>
        <p className="text-2xl font-bold">
          Ivan Alberto Romero Wells - A00833623
        </p>
        <p className="text-2xl font-bold"></p>
      </main>
    </>
  );
};

export default Home;
